site_name: Notes
# docs_dir: Python
# theme: readthedocs

theme:
  name: material
  features:
    - tabs
  palette:
    # scheme: slate # Dark Theme
    primary: white
    accent: red

markdown_extensions:
  - codehilite
  - admonition



extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/squidfunk
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/squidfunk
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/squidfunk
