site_name: Programming
docs_dir: website

# Theme configuration
theme:
  name: material
  feature:
    tabs: true


markdown_extensions:
  - codehilite:
      linenums: true
  - admonition

nav:
  - Home: 'index.md'
  - Python:
    - 1. Core Python: 'python/core.md'
    - 2. Functions: 'python/functions.md'
    - 3. Seperating code: 'python/modules_and_packages.md'
    - 4. OOP: 'python/object_oriented_python.md'
    - 5. Projects: 'python/projects.md'
  - Java:
    - 1. The Java World: 'java/overview_of_the_java_world.md'
    - 2. Core Java: 'java/core_java.md'
    - 3. Collections: 'java/collections.md'
    - 4. Core Platform: 'java/core_platform.md'
    - 5. Generics : 'java/generics.md'
    - 6. Database with JDBC : 'java/database_with_JDBC.md'

