site_name: Programming
docs_dir: website

# Theme configuration
theme:
  name: material
  feature:
    tabs: true


markdown_extensions:
  - codehilite:
      linenums: true
  - admonition

nav:
  - Home: 'index.md'
  - Python:
    - 1. Core Python: 'python/core.md'
    - 2. Functions: 'python/functions.md'
    - 3. Seperating code: 'python/modules_and_packages.md'
    - 4. OOP: 'python/object_oriented_python.md'
    - 5. Projects: 'python/projects.md'
